xxl:
  job:
    accessToken: xxx
    admin:
      addresses: xxx
    executor:
      appname: spider-flow-executor-pro
      address:
      ip:
      port: 9999
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30

app:
  id: spider-flow
apollo:
  config-service: http://192.168.5.131:9980
  bootstrap:
    enabled: true
    eagerLoad:
      enabled: true
    namespaces: application

common:
  email: xxx
  phone: xxx
  password: xxx

ikuuu:
  username: ${common.email}
  password: ${common.password}

jingjiang:
  username: ${common.phone}
  password: ${common.password}

juejin:
  username: ${common.phone}
  password: ${common.password}

liandi:
  username: ${common.phone}
  password: ${common.password}

