xxl:
  job:
    accessToken: ${xxl.job.accessToken}
    admin:
      address: ${xxl.job.admin.address}
    executor:
      appname: spider-flow-executor-pro
      address:
      ip:
      port: 9999
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30